const KEY='framex-store-v11';
const LEGACY=['framex-store-v10','framex-store-v9','framex-store-v8','framex-store-v7','framex-store-v5','framex-store-v2'];
let STATE=null;

const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const clone=v=>JSON.parse(JSON.stringify(v));

const BUSINESS_CATEGORIES=[
'Agência de marketing','Advocacia','Academia','Arquitetura','Automotivo','Bar / Pub','Barbearia','Beleza / Estética','Clínica médica','Clínica odontológica','Consultoria','Contabilidade','Cursos / Educação','E-commerce / Loja virtual','Eventos','Farmácia','Floricultura','Fotografia','Imobiliária','Loja de roupas / Moda','Marketplace','Nutrição','Padaria / Confeitaria','Pet shop','Portfólio profissional','Psicologia','Restaurante / Gastronomia','Salão de beleza','Saúde / Bem-estar','Site de relacionamento','Site para escolher filmes e séries','Software / SaaS','Tecnologia / Startup','Turismo / Hotelaria','Outro'
];
const VIDEO_CATEGORIES=['Publicidade com IA','Avatar com IA','Modelo virtual','TikTok Shop','Vídeo institucional','Criativo para anúncio','Conteúdo para redes sociais','Demonstração de produto','UGC com IA','Motion / Animação','Outro'];
const IMAGE_CATEGORIES=['Modelo virtual','Produto / E-commerce','Criativo publicitário','Social media','Identidade visual','Antes e depois','Editorial / Fashion','Mockup','Banner / Campanha','Outro'];

const defaults={
 projects:[],videos:[],images:[],restorations:[],reviews:[],leads:[],ideas:[],campaigns:[],
 settings:{
  whatsapp:'5521989784737', phone:'(21) 98978-4737', location:'Todos os Santos\nRio de Janeiro — RJ', socialLabel:'Frame X Studio',
  instagramPersonal:'https://instagram.com/eucaiocavalcante', instagramFrameX:'',
  heroTitle:'Ideias que viram experiências digitais.',
  heroText:'Sites, Inteligência Artificial, conteúdo e soluções digitais criadas com estratégia, tecnologia e atenção aos detalhes.'
 }
};

function normalizeItem(x,i){return {...x,id:x.id||uid(),published:x.published!==false,status:x.status||((x.published!==false)?'published':'draft'),featured:!!x.featured,favorite:!!x.favorite,order:x.order??i};}
function migrate(raw){
 const d=clone(defaults); if(!raw) return d;
 for(const k of ['projects','videos','images','restorations','reviews','leads','ideas','campaigns']) if(Array.isArray(raw[k])) d[k]=raw[k];
 if(Array.isArray(raw.media)){ d.videos=raw.media.filter(x=>x.type==='video'); d.images=raw.media.filter(x=>x.type==='image'); }
 d.settings={...d.settings,...(raw.settings||{})};
 d.projects=d.projects.map(normalizeItem); d.videos=d.videos.map(normalizeItem); d.images=d.images.map(normalizeItem); d.restorations=d.restorations.map(normalizeItem);
 return d;
}
function localLegacyState(){
 try{
  let raw=localStorage.getItem(KEY);
  if(!raw){for(const k of LEGACY){raw=localStorage.getItem(k); if(raw) break;}}
  return raw?migrate(JSON.parse(raw)):null;
 }catch{return null}
}
function hasContent(s){return !!s && ['projects','videos','images','restorations','reviews','leads','ideas'].some(k=>Array.isArray(s[k])&&s[k].length>0)}
function load(){return STATE||migrate(null)}
async function loadRemote(){
 const r=await fetch('/api/state',{credentials:'same-origin'}); const j=await r.json();
 if(!r.ok) throw new Error(j.error||'Falha ao carregar dados online.');
 STATE=migrate(j.state||null); return STATE;
}
let saveChain=Promise.resolve();
function save(s,rerender=true){
 STATE=migrate(s); if(rerender) render();
 const snapshot=clone(STATE);
 saveChain=saveChain.then(async()=>{
   const r=await fetch('/api/state',{method:'PUT',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify({state:snapshot})});
   const j=await r.json().catch(()=>({})); if(!r.ok) throw new Error(j.error||'Falha ao salvar online.');
 }).catch(err=>{console.error(err);alert('Não consegui salvar no Cloudflare: '+err.message)});
 return saveChain;
}
async function putBlob(file){
 const fd=new FormData(); fd.append('file',file);
 const r=await fetch('/api/upload',{method:'POST',credentials:'same-origin',body:fd}); const j=await r.json().catch(()=>({}));
 if(!r.ok) throw new Error(j.error||'Falha no upload.'); return j.key;
}
async function delBlob(id){if(!id)return;await fetch('/api/media/'+encodeURIComponent(id),{method:'DELETE',credentials:'same-origin'}).catch(()=>{})}
const mediaUrl=id=>id?'/api/media/'+encodeURIComponent(id):'';

function authScreen(mode='login',configured=true){
 $('#adminApp').classList.add('hidden');
 $('#auth').innerHTML=`<div class="authPage"><div class="authCard glass"><div class="authBrand"><img src="assets/frame-x-logo.png" alt="Frame X"><div><b>FRAME X</b><small>STUDIO · ADMIN ONLINE</small></div></div><div class="authKicker">PAINEL ADMINISTRATIVO</div><h1>${mode==='register'?'Criar acesso':'Bem-vindo de volta'}</h1><p>${mode==='register'?'Crie seu acesso seguro. Ele ficará salvo no Cloudflare D1.':'Entre para gerenciar o site publicado, mídias e leads em tempo real.'}</p><div class="authTabs"><button id="tabLogin" class="${mode==='login'?'active':''}">Entrar</button><button id="tabRegister" class="${mode==='register'?'active':''}">${configured?'Alterar acesso':'Cadastrar'}</button></div><form id="authForm" class="authForm"><label>Login<input id="authUser" autocomplete="username" placeholder="Seu login" required></label><label>Senha<input id="authPass" type="password" autocomplete="current-password" placeholder="Sua senha" minlength="6" required></label>${mode==='register'?'<label>Confirmar senha<input id="authPass2" type="password" placeholder="Repita sua senha" minlength="6" required></label>':''}<button class="btn" type="submit">${mode==='register'?'Salvar acesso →':'Entrar →'}</button></form><p id="authMsg" class="authMsg"></p><small class="authNote">Acesso protegido por sessão segura. Conteúdo no D1 e arquivos no R2.</small></div></div>`;
 $('#tabLogin').onclick=()=>authScreen('login',configured); $('#tabRegister').onclick=()=>authScreen('register',configured);
 $('#authForm').onsubmit=async e=>{e.preventDefault();const u=$('#authUser').value.trim(),p=$('#authPass').value,msg=$('#authMsg');msg.textContent='Aguarde...';
  if(mode==='register'&&p!==$('#authPass2').value){msg.textContent='As senhas não coincidem.';return}
  const endpoint=mode==='register'?'/api/auth/register':'/api/auth/login';
  try{const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify({username:u,password:p})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Não foi possível entrar.');await openAdmin();}
  catch(err){msg.textContent=err.message}
 };
}

let current='dashboard';
async function openAdmin(){
 $('#auth').innerHTML=''; $('#adminApp').classList.remove('hidden');
 try{
   await loadRemote();
   const legacy=localLegacyState();
   if(!hasContent(STATE)&&hasContent(legacy)){
     STATE=legacy; await fetch('/api/state',{method:'PUT',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify({state:STATE})});
   }
 }catch(err){alert('Erro ao carregar o painel online: '+err.message)}
 $$('aside [data-tab]').forEach(b=>b.onclick=()=>{current=b.dataset.tab;$$('aside [data-tab]').forEach(x=>x.classList.toggle('active',x===b));render();});
 $('#logout').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST',credentials:'same-origin'});location.reload()}; render();
}
const content=()=>$('#content');
function render(){
 const s=load(); const titles={dashboard:'Dashboard',projects:'Sites / Portfólio',videos:'Vídeos',images:'Imagens',restorations:'Restauração de Fotos',leads:'Leads',ideas:'Ideias & Ofertas',reviews:'Avaliações',settings:'Site & Configurações'};
 $('#title').textContent=titles[current]||'Admin';
 ({dashboard:renderDashboard,projects:renderProjects,videos:renderVideos,images:renderImages,restorations:renderRestorations,leads:renderLeads,ideas:renderIdeas,reviews:renderReviews,settings:renderSettings}[current]||renderDashboard)(s);
}
function metric(n,label){return `<div class="metric"><b>${n}</b><span>${label}</span></div>`}
function renderDashboard(s){
 const drafts=[...s.projects,...s.videos,...s.images,...s.restorations].filter(x=>x.status==='draft'||x.published===false).length;
 content().innerHTML=`<div class="dashboardGrid">${metric(s.projects.length,'Sites')}${metric(s.videos.length,'Vídeos')}${metric(s.images.length,'Imagens')}${metric(s.restorations.length,'Restaurações')}${metric(s.leads.filter(x=>x.status==='Novo').length,'Leads novos')}${metric(drafts,'Rascunhos')}</div><div class="settingsGrid"><div class="adminPanel"><div class="panelHead"><div><h3>Atalhos rápidos</h3><p>Cadastre conteúdo em poucos cliques.</p></div></div><div class="backupActions"><button class="btn mini" id="dashProject">+ Site</button><button class="btn mini" id="dashVideo">+ Vídeo</button><button class="btn mini" id="dashImage">+ Imagem</button><button class="btn mini" id="dashRestoration">+ Restauração</button></div></div><div class="adminPanel"><h3>Fila comercial</h3><p><b>${s.leads.filter(x=>x.status==='Novo').length}</b> lead(s) aguardando contato.</p><button class="btn mini ghost" id="goLeads">Abrir leads</button></div></div><div class="adminPanel"><h3>Destaques atuais</h3><div class="managerList">${[...s.projects,...s.videos,...s.images,...s.restorations].filter(x=>x.featured).slice(0,6).map(x=>`<div class="managerItem leadItem"><div class="managerInfo"><div class="managerBadges"><span>DESTAQUE</span></div><h4>${esc(x.name||x.title||'Conteúdo')}</h4></div></div>`).join('')||'<div class="emptyState">Nenhum destaque marcado.</div>'}</div></div>`;
 $('#dashProject').onclick=()=>projectEditor(s); $('#dashVideo').onclick=()=>videoEditor(s); $('#dashImage').onclick=()=>imageEditor(s); $('#dashRestoration').onclick=()=>restorationEditor(s); $('#goLeads').onclick=()=>{current='leads';render()};
}
function badges(x){return `<div class="managerBadges"><span class="${x.published!==false&&x.status!=='draft'?'ok':'warn'}">${x.published!==false&&x.status!=='draft'?'PUBLICADO':'RASCUNHO'}</span>${x.featured?'<span>DESTAQUE</span>':''}${x.favorite?'<span>★ FAVORITO</span>':''}</div>`}
function actionButtons(type,i,len){return `<div class="managerActions"><button data-up="${type}:${i}" ${i===0?'disabled':''}>↑</button><button data-down="${type}:${i}" ${i===len-1?'disabled':''}>↓</button><button data-preview="${type}:${i}">Prévia</button><button data-dup="${type}:${i}">Duplicar</button><button data-edit="${type}:${i}">Editar</button><button data-toggle="${type}:${i}">Publicar/ocultar</button><button class="danger" data-del="${type}:${i}">Excluir</button></div>`}
function bindCommon(s,type,editor){const list=s[type];
 $$(`[data-edit^="${type}:"]`).forEach(b=>b.onclick=()=>editor(s,+b.dataset.edit.split(':')[1]));
 $$(`[data-dup^="${type}:"]`).forEach(b=>b.onclick=()=>{const i=+b.dataset.dup.split(':')[1],copy=clone(list[i]);copy.id=uid();copy.name=copy.name?copy.name+' — cópia':copy.name;copy.title=copy.title?copy.title+' — cópia':copy.title;copy.featured=false;copy.published=false;copy.status='draft';list.splice(i+1,0,copy);save(s)});
 $$(`[data-preview^="${type}:"]`).forEach(b=>b.onclick=()=>previewItem(type,list[+b.dataset.preview.split(':')[1]]));
 $$(`[data-toggle^="${type}:"]`).forEach(b=>b.onclick=()=>{const x=list[+b.dataset.toggle.split(':')[1]];x.published=!(x.published!==false);x.status=x.published?'published':'draft';save(s)});
 $$(`[data-del^="${type}:"]`).forEach(b=>b.onclick=async()=>{const i=+b.dataset.del.split(':')[1];if(!confirm('Excluir este item?'))return;if(list[i].assetId)await delBlob(list[i].assetId);if(list[i].beforeAssetId)await delBlob(list[i].beforeAssetId);if(list[i].afterAssetId)await delBlob(list[i].afterAssetId);list.splice(i,1);save(s)});
 $$(`[data-up^="${type}:"]`).forEach(b=>b.onclick=()=>{const i=+b.dataset.up.split(':')[1];if(i>0){[list[i-1],list[i]]=[list[i],list[i-1]];save(s)}});
 $$(`[data-down^="${type}:"]`).forEach(b=>b.onclick=()=>{const i=+b.dataset.down.split(':')[1];if(i<list.length-1){[list[i+1],list[i]]=[list[i],list[i+1]];save(s)}});
}
function previewItem(type,x){
 let body='';
 if(type==='projects'){body=`<div class="previewPane"><h3>${esc(x.name||'Projeto')}</h3><p>${esc(x.description||'')}</p>${x.url?`<a class="btn mini" href="${esc(x.url)}" target="_blank" rel="noopener">Abrir site ↗</a>`:''}${x.image?`<img src="${esc(x.image)}" alt="">`:''}</div>`}
 else if(type==='videos'){body=`<div class="previewPane"><h3>${esc(x.title||'Vídeo')}</h3>${x.url?`<video src="${esc(x.url)}" controls muted playsinline></video>`:x.assetId?`<video src="${mediaUrl(x.assetId)}" controls muted playsinline></video>`:'<p>Sem vídeo.</p>'}</div>`}
 else if(type==='images'){body=`<div class="previewPane"><h3>${esc(x.title||'Imagem')}</h3>${x.url?`<img src="${esc(x.url)}" alt="">`:x.assetId?`<img src="${mediaUrl(x.assetId)}" alt="">`:'<p>Sem imagem.</p>'}</div>`}
 else if(type==='restorations'){body=`<div class="previewPane"><h3>${esc(x.title||'Restauração')}</h3><p>Prévia do antes/depois no site público.</p></div>`}
 modal(`<div class="modalHead"><div><small>PRÉVIA</small><h2>Como ficará no site</h2></div><button data-close-modal>×</button></div>${body}<div class="modalActions"><a class="btn" href="index.html" target="_blank">Abrir site</a></div>`)
}
function mediaSizeWarning(file,kind){if(!file)return true;const mb=file.size/1024/1024,limit=kind==='video'?8:5;if(mb>limit){return confirm(`Este arquivo tem ${mb.toFixed(1)} MB. Para manter o site rápido, recomendamos até ${limit} MB. Deseja continuar mesmo assim?`)}return true}
function filterManagerList(q,status){const query=(q||'').trim().toLowerCase();document.querySelectorAll('.managerList .managerItem').forEach(el=>{const text=el.textContent.toLowerCase(),st=el.dataset.status||'';el.style.display=(!query||text.includes(query))&&(!status||status==='all'||st===status)?'':'none'})}
function bindManagerTools(){const q=$('#managerSearch'),st=$('#managerStatus');if(q)q.oninput=()=>filterManagerList(q.value,st?.value);if(st)st.onchange=()=>filterManagerList(q?.value,st.value)}
function managerTools(){return `<div class="managerTools"><input id="managerSearch" placeholder="Buscar por nome, categoria ou descrição"><select id="managerStatus"><option value="all">Todos os status</option><option value="published">Publicados</option><option value="draft">Rascunhos</option></select></div>`}
function modal(html){$('#modalRoot').innerHTML=`<div class="modalBackdrop"><div class="modalBox">${html}</div></div>`;$$('[data-close-modal]').forEach(b=>b.onclick=closeModal)}
function closeModal(){$('#modalRoot').innerHTML=''}
function optionList(items,value){return items.map(x=>`<option ${x===value?'selected':''}>${esc(x)}</option>`).join('')}
function generateDescription(kind,name,category){const n=name||'Este projeto';
 const siteMap={
  'Floricultura':`${n} é uma experiência digital criada para apresentar flores, presentes e arranjos de forma elegante, facilitar pedidos e aproximar a marca de seus clientes.`,
  'Padaria / Confeitaria':`${n} apresenta produtos, especialidades e informações da marca de forma acolhedora, moderna e pensada para facilitar pedidos e visitas.`,
  'Site de relacionamento':`${n} foi pensado para criar conexões de forma simples, intuitiva e responsiva, com uma experiência focada em descoberta e interação.`,
  'Site para escolher filmes e séries':`${n} transforma a escolha do que assistir em uma experiência rápida e divertida, usando preferências para sugerir conteúdos de forma personalizada.`,
  'E-commerce / Loja virtual':`${n} foi desenvolvido para valorizar produtos, simplificar a jornada de compra e criar uma experiência comercial clara, rápida e responsiva.`,
  'Advocacia':`${n} apresenta serviços jurídicos com clareza, credibilidade e uma comunicação profissional, facilitando o primeiro contato com potenciais clientes.`
 };
 if(kind==='project') return siteMap[category]||`${n} é um projeto digital desenvolvido para o segmento de ${category||'negócios'}, unindo apresentação profissional, navegação responsiva e uma experiência pensada para o público da marca.`;
 if(kind==='video') return `${n} é um conteúdo de ${category||'vídeo digital'} criado pela Frame X Studio com foco em impacto visual, comunicação clara e apresentação profissional da marca ou produto.`;
 return `${n} é uma peça visual de ${category||'conteúdo digital'} desenvolvida para valorizar identidade, produto e comunicação com acabamento profissional e atenção aos detalhes.`;
}

function renderProjects(s){content().innerHTML=`<div class="adminPanel"><div class="panelHead"><div><h3>Sites de portfólio</h3><p>Cadastre link, segmento, descrição e prévia. A prévia ao vivo usa o próprio link do projeto. Se o site bloquear iframe, use uma screenshot longa.</p></div><button id="newProject" class="btn mini">+ Adicionar site</button></div>${managerTools()}<div class="managerList">${s.projects.map((p,i)=>`<article class="managerItem" data-status="${p.published!==false&&p.status!=='draft'?'published':'draft'}"><img class="managerThumb" src="${esc(p.assetId?mediaUrl(p.assetId):(p.image||'assets/project-1.png'))}"><div class="managerInfo">${badges(p)}<h4>${esc(p.name||'Projeto')}</h4><p>${esc(p.category||'')} · ${esc(p.description||'')}</p></div>${actionButtons('projects',i,s.projects.length)}</article>`).join('')||'<div class="emptyState">Nenhum site cadastrado.</div>'}</div></div>`;$('#newProject').onclick=()=>projectEditor(s);bindManagerTools();bindCommon(s,'projects',projectEditor)}
function projectEditor(s,i=null){const p=i==null?{id:uid(),name:'',category:'Site institucional',description:'',url:'',previewMode:'live',image:'',assetId:'',published:true,featured:false,favorite:false}:clone(s.projects[i]);
 modal(`<div class="modalHead"><div><small>SITE / PORTFÓLIO</small><h2>${i==null?'Novo site':'Editar site'}</h2></div><button data-close-modal>×</button></div><form id="projectForm" class="editorForm"><div class="formGrid"><label>Nome<input id="pName" value="${esc(p.name)}" required></label><label>Categoria / segmento<select id="pCategory">${optionList(BUSINESS_CATEGORIES,p.category)}</select></label></div><label>Descrição<div class="inlineField"><textarea id="pDescription" rows="4">${esc(p.description)}</textarea><button class="btn mini ghost" type="button" id="generateProjectDescription">Gerar descrição</button></div></label><label>Link real do site<input id="pUrl" value="${esc(p.url)}" placeholder="https://..." required></label><div class="formGrid"><label>Tipo de prévia<select id="pPreview"><option value="live" ${(p.previewMode==='live'||p.previewMode==='auto')?'selected':''}>Site ao vivo pelo link (iframe)</option><option value="image" ${p.previewMode==='image'?'selected':''}>Screenshot longa / imagem</option></select></label><label>Imagem por URL<input id="pImage" value="${esc(p.image||'')}" placeholder="https://..."></label></div><label class="uploadBox">Ou envie screenshot longa<input id="pFile" type="file" accept="image/*"></label><div class="checkRow"><label><input id="pPublished" type="checkbox" ${p.published!==false?'checked':''}> Publicar</label><label><input id="pFeatured" type="checkbox" ${p.featured?'checked':''}> Destaque</label><label><input id="pFavorite" type="checkbox" ${p.favorite?'checked':''}> Favorito interno</label></div><div class="modalActions"><button type="button" class="btn ghost" data-close-modal>Cancelar</button><button class="btn" type="submit">Salvar site</button></div></form>`);
 $('#generateProjectDescription').onclick=()=>$('#pDescription').value=generateDescription('project',$('#pName').value.trim(),$('#pCategory').value);
 $('#projectForm').onsubmit=async e=>{e.preventDefault();const file=$('#pFile').files[0];if(file&&!mediaSizeWarning(file,'image'))return;if(file){if(p.assetId)await delBlob(p.assetId);p.assetId=await putBlob(file);p.image=''}Object.assign(p,{name:$('#pName').value.trim(),category:$('#pCategory').value,description:$('#pDescription').value.trim(),url:$('#pUrl').value.trim(),previewMode:$('#pPreview').value,image:$('#pImage').value.trim(),published:$('#pPublished').checked,status:$('#pPublished').checked?'published':'draft',featured:$('#pFeatured').checked,favorite:$('#pFavorite').checked});if(i==null)s.projects.unshift(p);else s.projects[i]=p;save(s,false);closeModal();render();};
}

function renderVideos(s){content().innerHTML=`<div class="adminPanel"><div class="panelHead"><div><h3>Vídeos</h3><p>Vídeos do portfólio, IA, TikTok Shop, publicidade e conteúdo.</p></div><button id="newVideo" class="btn mini">+ Adicionar vídeo</button></div>${managerTools()}<div class="managerList">${s.videos.map((v,i)=>`<article class="managerItem" data-status="${v.published!==false&&v.status!=='draft'?'published':'draft'}"><div class="managerThumb mediaPlaceholder">▶</div><div class="managerInfo">${badges(v)}<h4>${esc(v.title||'Vídeo')}</h4><p>${esc(v.category||'')} · ${v.ratio==='horizontal'?'16:9':v.ratio==='square'?'1:1':'9:16'} · ${esc(v.description||'')}</p></div>${actionButtons('videos',i,s.videos.length)}</article>`).join('')||'<div class="emptyState">Nenhum vídeo cadastrado.</div>'}</div></div>`;$('#newVideo').onclick=()=>videoEditor(s);bindManagerTools();bindCommon(s,'videos',videoEditor)}
function videoEditor(s,i=null){const v=i==null?{id:uid(),title:'',category:'Publicidade com IA',description:'',url:'',assetId:'',published:true,featured:false,favorite:false,ratio:'vertical'}:clone(s.videos[i]);
 modal(`<div class="modalHead"><div><small>VÍDEO</small><h2>${i==null?'Novo vídeo':'Editar vídeo'}</h2></div><button data-close-modal>×</button></div><form id="videoForm" class="editorForm"><div class="formGrid"><label>Título<input id="vTitle" value="${esc(v.title)}" required></label><label>Categoria<select id="vCategory">${optionList(VIDEO_CATEGORIES,v.category)}</select></label><label>Formato<select id="vRatio"><option value="vertical" ${v.ratio==='vertical'?'selected':''}>Vertical · 9:16</option><option value="horizontal" ${v.ratio==='horizontal'?'selected':''}>Horizontal · 16:9</option><option value="square" ${v.ratio==='square'?'selected':''}>Quadrado · 1:1</option></select></label></div><label>Descrição<div class="inlineField"><textarea id="vDescription" rows="4">${esc(v.description)}</textarea><button class="btn mini ghost" type="button" id="generateVideoDescription">Gerar descrição</button></div></label><label>Link do vídeo / YouTube<input id="vUrl" value="${esc(v.url||'')}" placeholder="https://..."></label><label class="uploadBox">Ou envie o arquivo de vídeo<input id="vFile" type="file" accept="video/*"></label><div class="checkRow"><label><input id="vPublished" type="checkbox" ${v.published!==false?'checked':''}> Publicar</label><label><input id="vFeatured" type="checkbox" ${v.featured?'checked':''}> Destaque</label><label><input id="vFavorite" type="checkbox" ${v.favorite?'checked':''}> Favorito interno</label></div><div class="modalActions"><button type="button" class="btn ghost" data-close-modal>Cancelar</button><button class="btn" type="submit">Salvar vídeo</button></div></form>`);
 $('#generateVideoDescription').onclick=()=>$('#vDescription').value=generateDescription('video',$('#vTitle').value.trim(),$('#vCategory').value);
 $('#videoForm').onsubmit=async e=>{e.preventDefault();const file=$('#vFile').files[0];if(file&&!mediaSizeWarning(file,'video'))return;if(file){if(v.assetId)await delBlob(v.assetId);v.assetId=await putBlob(file)}Object.assign(v,{title:$('#vTitle').value.trim(),category:$('#vCategory').value,ratio:$('#vRatio').value,description:$('#vDescription').value.trim(),url:$('#vUrl').value.trim(),published:$('#vPublished').checked,status:$('#vPublished').checked?'published':'draft',featured:$('#vFeatured').checked,favorite:$('#vFavorite').checked});if(i==null)s.videos.unshift(v);else s.videos[i]=v;save(s,false);closeModal();render();};
}

function renderImages(s){content().innerHTML=`<div class="adminPanel"><div class="panelHead"><div><h3>Imagens</h3><p>Modelos virtuais, criativos, produtos, campanhas e peças visuais.</p></div><button id="newImage" class="btn mini">+ Adicionar imagem</button></div>${managerTools()}<div class="managerList">${s.images.map((v,i)=>`<article class="managerItem" data-status="${v.published!==false&&v.status!=='draft'?'published':'draft'}"><img class="managerThumb" src="${esc(v.assetId?mediaUrl(v.assetId):(v.url||v.image||'assets/project-1.png'))}"><div class="managerInfo">${badges(v)}<h4>${esc(v.title||'Imagem')}</h4><p>${esc(v.category||'')} · ${v.ratio==='horizontal'?'16:9':v.ratio==='square'?'1:1':'9:16'} · ${esc(v.description||'')}</p></div>${actionButtons('images',i,s.images.length)}</article>`).join('')||'<div class="emptyState">Nenhuma imagem cadastrada.</div>'}</div></div>`;$('#newImage').onclick=()=>imageEditor(s);bindManagerTools();bindCommon(s,'images',imageEditor)}
function imageEditor(s,i=null){const v=i==null?{id:uid(),title:'',category:'Criativo publicitário',description:'',url:'',assetId:'',published:true,featured:false,favorite:false,ratio:'vertical'}:clone(s.images[i]);
 modal(`<div class="modalHead"><div><small>IMAGEM</small><h2>${i==null?'Nova imagem':'Editar imagem'}</h2></div><button data-close-modal>×</button></div><form id="imageForm" class="editorForm"><div class="formGrid"><label>Título<input id="iTitle" value="${esc(v.title)}" required></label><label>Categoria<select id="iCategory">${optionList(IMAGE_CATEGORIES,v.category)}</select></label><label>Formato<select id="iRatio"><option value="vertical" ${v.ratio==='vertical'?'selected':''}>Vertical · 9:16</option><option value="horizontal" ${v.ratio==='horizontal'?'selected':''}>Horizontal · 16:9</option><option value="square" ${v.ratio==='square'?'selected':''}>Quadrado · 1:1</option></select></label></div><label>Descrição<div class="inlineField"><textarea id="iDescription" rows="4">${esc(v.description)}</textarea><button class="btn mini ghost" type="button" id="generateImageDescription">Gerar descrição</button></div></label><label>Imagem por URL<input id="iUrl" value="${esc(v.url||'')}" placeholder="https://..."></label><label class="uploadBox">Ou envie a imagem<input id="iFile" type="file" accept="image/*"></label><div class="checkRow"><label><input id="iPublished" type="checkbox" ${v.published!==false?'checked':''}> Publicar</label><label><input id="iFeatured" type="checkbox" ${v.featured?'checked':''}> Destaque</label><label><input id="iFavorite" type="checkbox" ${v.favorite?'checked':''}> Favorito interno</label></div><div class="modalActions"><button type="button" class="btn ghost" data-close-modal>Cancelar</button><button class="btn" type="submit">Salvar imagem</button></div></form>`);
 $('#generateImageDescription').onclick=()=>$('#iDescription').value=generateDescription('image',$('#iTitle').value.trim(),$('#iCategory').value);
 $('#imageForm').onsubmit=async e=>{e.preventDefault();const file=$('#iFile').files[0];if(file&&!mediaSizeWarning(file,'image'))return;if(file){if(v.assetId)await delBlob(v.assetId);v.assetId=await putBlob(file)}Object.assign(v,{title:$('#iTitle').value.trim(),category:$('#iCategory').value,ratio:$('#iRatio').value,description:$('#iDescription').value.trim(),url:$('#iUrl').value.trim(),published:$('#iPublished').checked,status:$('#iPublished').checked?'published':'draft',featured:$('#iFeatured').checked,favorite:$('#iFavorite').checked});if(i==null)s.images.unshift(v);else s.images[i]=v;save(s,false);closeModal();render();};
}

function renderRestorations(s){content().innerHTML=`<div class="adminPanel"><div class="panelHead"><div><h3>Restauração de Fotos</h3><p>Cadastre o antes e o depois, escolha o formato e publique a comparação interativa na página inicial.</p></div><button id="newRestoration" class="btn mini">+ Adicionar restauração</button></div>${managerTools()}<div class="managerList">${s.restorations.map((r,i)=>`<article class="managerItem" data-status="${r.published!==false&&r.status!=='draft'?'published':'draft'}"><div class="managerThumb mediaPlaceholder">◐</div><div class="managerInfo">${badges(r)}<h4>${esc(r.title||'Restauração')}</h4><p>${r.ratio==='vertical'?'9:16 vertical':'16:9 horizontal'} · ${esc(r.description||'')}</p></div>${actionButtons('restorations',i,s.restorations.length)}</article>`).join('')||'<div class="emptyState">Nenhuma restauração cadastrada.</div>'}</div></div>`;$('#newRestoration').onclick=()=>restorationEditor(s);bindManagerTools();bindCommon(s,'restorations',restorationEditor)}
function restorationEditor(s,i=null){const r=i==null?{id:uid(),title:'',category:'Restauração de Fotos',description:'',beforeUrl:'',afterUrl:'',beforeAssetId:'',afterAssetId:'',ratio:'horizontal',published:true,featured:false,favorite:false}:clone(s.restorations[i]);
 modal(`<div class="modalHead"><div><small>RESTAURAÇÃO DE FOTOS</small><h2>${i==null?'Nova restauração':'Editar restauração'}</h2></div><button data-close-modal>×</button></div><form id="restorationForm" class="editorForm"><div class="formGrid"><label>Título<input id="rTitle" value="${esc(r.title)}" placeholder="Ex.: Foto de família restaurada" required></label><label>Formato<select id="rRatio"><option value="horizontal" ${r.ratio==='horizontal'?'selected':''}>Horizontal · 16:9</option><option value="vertical" ${r.ratio==='vertical'?'selected':''}>Vertical · 9:16</option></select></label></div><label>Descrição<textarea id="rDescription" rows="3" placeholder="Ex.: Recuperação de nitidez, cor e detalhes mantendo a aparência natural.">${esc(r.description||'')}</textarea></label><div class="formGrid"><label>Imagem ANTES por URL<input id="rBeforeUrl" value="${esc(r.beforeUrl||'')}" placeholder="https://..."></label><label>Imagem DEPOIS por URL<input id="rAfterUrl" value="${esc(r.afterUrl||'')}" placeholder="https://..."></label></div><div class="formGrid"><label class="uploadBox">Ou envie a imagem ANTES<input id="rBeforeFile" type="file" accept="image/*"></label><label class="uploadBox">Ou envie a imagem DEPOIS<input id="rAfterFile" type="file" accept="image/*"></label></div><div class="checkRow"><label><input id="rPublished" type="checkbox" ${r.published!==false?'checked':''}> Publicar</label><label><input id="rFeatured" type="checkbox" ${r.featured?'checked':''}> Destaque</label><label><input id="rFavorite" type="checkbox" ${r.favorite?'checked':''}> Favorito interno</label></div><div class="modalActions"><button type="button" class="btn ghost" data-close-modal>Cancelar</button><button class="btn" type="submit">Salvar restauração</button></div></form>`);
 $('#restorationForm').onsubmit=async e=>{e.preventDefault();const bf=$('#rBeforeFile').files[0],af=$('#rAfterFile').files[0];if((bf&&!mediaSizeWarning(bf,'image'))||(af&&!mediaSizeWarning(af,'image')))return;if(bf){if(r.beforeAssetId)await delBlob(r.beforeAssetId);r.beforeAssetId=await putBlob(bf);r.beforeUrl=''}if(af){if(r.afterAssetId)await delBlob(r.afterAssetId);r.afterAssetId=await putBlob(af);r.afterUrl=''}Object.assign(r,{title:$('#rTitle').value.trim(),description:$('#rDescription').value.trim(),ratio:$('#rRatio').value,beforeUrl:bf?'':$('#rBeforeUrl').value.trim(),afterUrl:af?'':$('#rAfterUrl').value.trim(),published:$('#rPublished').checked,status:$('#rPublished').checked?'published':'draft',featured:$('#rFeatured').checked,favorite:$('#rFavorite').checked});if(!r.beforeAssetId&&!r.beforeUrl||!r.afterAssetId&&!r.afterUrl){alert('Adicione as imagens de antes e depois.');return}if(i==null)s.restorations.unshift(r);else s.restorations[i]=r;save(s,false);closeModal();render();};
}
function renderLeads(s){const statuses=['Novo','Em contato','Proposta enviada','Convertido','Arquivado'];content().innerHTML=`<div class="adminPanel"><div class="panelHead"><div><h3>Leads</h3><p>Contatos enviados pelo formulário da página inicial.</p></div></div><div class="managerList">${s.leads.map((l,i)=>`<article class="managerItem leadItem"><div class="managerInfo"><div class="managerBadges"><span>${esc(l.service||'CONTATO')}</span></div><h4>${esc(l.name||'Lead')}</h4><p>${esc(l.idea||'')}</p><small>${esc(l.whatsapp||'')} ${l.email?'· '+esc(l.email):''}</small></div><div class="managerActions"><select data-lead-status="${i}">${statuses.map(st=>`<option ${st===l.status?'selected':''}>${st}</option>`).join('')}</select><a class="btn mini" target="_blank" rel="noopener" href="https://wa.me/55${String(l.whatsapp||'').replace(/\D/g,'').replace(/^55/,'')}">WhatsApp</a><button class="danger" data-lead-del="${i}">Excluir</button></div></article>`).join('')||'<div class="emptyState">Nenhum lead recebido ainda.</div>'}</div></div>`;$$('[data-lead-status]').forEach(el=>el.onchange=()=>{s.leads[+el.dataset.leadStatus].status=el.value;save(s)});$$('[data-lead-del]').forEach(el=>el.onclick=()=>{if(confirm('Excluir lead?')){s.leads.splice(+el.dataset.leadDel,1);save(s)}})}
function renderIdeas(s){content().innerHTML=`<div class="adminPanel"><div class="panelHead"><div><h3>Ideias & Ofertas</h3><p>Bloco interno para organizar novas ofertas. Nada daqui aparece no site automaticamente.</p></div><button class="btn mini" id="newIdea">+ Nova ideia</button></div><div class="managerList">${s.ideas.map((x,i)=>`<article class="managerItem leadItem"><div class="managerInfo"><h4>${esc(x.title||'Ideia')}</h4><p>${esc(x.text||'')}</p></div><div class="managerActions"><button class="danger" data-idea-del="${i}">Excluir</button></div></article>`).join('')||'<div class="emptyState">Nenhuma ideia cadastrada.</div>'}</div></div>`;$('#newIdea').onclick=()=>{const title=prompt('Título da ideia');if(!title)return;const text=prompt('Descrição da ideia')||'';s.ideas.unshift({id:uid(),title,text});save(s)};$$('[data-idea-del]').forEach(b=>b.onclick=()=>{s.ideas.splice(+b.dataset.ideaDel,1);save(s)})}
function renderReviews(s){content().innerHTML=`<div class="adminPanel"><div class="panelHead"><div><h3>Avaliações</h3><p>Cadastre e aprove depoimentos para exibição pública.</p></div><button class="btn mini" id="newReview">+ Avaliação</button></div><div class="managerList">${s.reviews.map((r,i)=>`<article class="managerItem leadItem"><div class="managerInfo"><div class="managerBadges"><span class="${r.approved?'ok':'warn'}">${r.approved?'APROVADA':'OCULTA'}</span></div><h4>${esc(r.name||'Cliente')}</h4><p>${esc(r.text||'')}</p></div><div class="managerActions"><button data-review-toggle="${i}">${r.approved?'Ocultar':'Aprovar'}</button><button class="danger" data-review-del="${i}">Excluir</button></div></article>`).join('')||'<div class="emptyState">Nenhuma avaliação.</div>'}</div></div>`;$('#newReview').onclick=()=>{const name=prompt('Nome do cliente');if(!name)return;const text=prompt('Comentário')||'';const role=prompt('Profissão / empresa (opcional)')||'';s.reviews.unshift({id:uid(),name,text,role,rating:5,approved:true});save(s)};$$('[data-review-toggle]').forEach(b=>b.onclick=()=>{const r=s.reviews[+b.dataset.reviewToggle];r.approved=!r.approved;save(s)});$$('[data-review-del]').forEach(b=>b.onclick=()=>{s.reviews.splice(+b.dataset.reviewDel,1);save(s)})}
function renderSettings(s){const x=s.settings;content().innerHTML=`<div class="settingsGrid"><div class="adminPanel"><h3>Conteúdo principal</h3><div class="editorForm"><label>Headline<input id="setHeroTitle" value="${esc(x.heroTitle)}"></label><label>Texto principal<textarea id="setHeroText" rows="4">${esc(x.heroText)}</textarea></label><label>WhatsApp<input id="setWhatsapp" value="${esc(x.whatsapp)}"></label><label>Telefone<input id="setPhone" value="${esc(x.phone)}"></label><label>Localização<textarea id="setLocation" rows="3">${esc(x.location)}</textarea></label><button class="btn" id="saveSettings">Salvar alterações</button></div></div><div class="adminPanel"><h3>Redes sociais</h3><div class="editorForm"><label>Instagram Caio<input id="setInstagramPersonal" value="${esc(x.instagramPersonal||'')}"></label><label>Instagram Frame X<input id="setInstagramFrameX" value="${esc(x.instagramFrameX||'')}"></label><label>Nome exibido<input id="setSocialLabel" value="${esc(x.socialLabel||'Frame X Studio')}"></label></div><h3>Backup</h3><div class="backupActions"><button class="btn mini ghost" id="exportBackup">Exportar JSON</button><label class="btn mini ghost">Importar JSON<input hidden id="importBackup" type="file" accept="application/json"></label></div></div></div>`;$('#saveSettings').onclick=()=>{Object.assign(s.settings,{heroTitle:$('#setHeroTitle').value,heroText:$('#setHeroText').value,whatsapp:$('#setWhatsapp').value,phone:$('#setPhone').value,location:$('#setLocation').value,instagramPersonal:$('#setInstagramPersonal').value,instagramFrameX:$('#setInstagramFrameX').value,socialLabel:$('#setSocialLabel').value});save(s)};$('#exportBackup').onclick=()=>{const blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='frame-x-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#importBackup').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());STATE=migrate(data);save(STATE);render()}catch{alert('Arquivo inválido.')}}}

async function bootstrap(){try{const r=await fetch('/api/auth/status',{credentials:'same-origin'});const j=await r.json();if(j.authenticated)await openAdmin();else authScreen(j.configured?'login':'register',!!j.configured)}catch(err){authScreen('login',true);$('#authMsg').textContent='API indisponível: '+err.message}}
bootstrap();
