const KEY='framex-store-v9';
const LEGACY=['framex-store-v8','framex-store-v7','framex-store-v5','framex-store-v2'];
const DB_NAME='framex-assets-v2', DB_STORE='files';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaults={projects:[],videos:[],images:[],reviews:[],leads:[],ideas:[],campaigns:[],settings:{whatsapp:'5521989784737',phone:'(21) 98978-4737',location:'Todos os Santos\nRio de Janeiro — RJ',socialLabel:'Frame X Studio',instagramPersonal:'https://instagram.com/eucaiocavalcante',instagramFrameX:'',heroTitle:'Ideias que viram experiências digitais.',heroText:'Sites, Inteligência Artificial, conteúdo e soluções digitais criadas com estratégia, tecnologia e atenção aos detalhes.'}};
const clone=v=>JSON.parse(JSON.stringify(v));
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function normalizeItem(x,i){return {...x,published:x.published!==false,status:x.status||((x.published!==false)?'published':'draft'),featured:!!x.featured,favorite:!!x.favorite,order:x.order??i};}
function migrate(raw){const d=clone(defaults);if(!raw)return d;for(const k of ['projects','videos','images','reviews','leads','ideas','campaigns'])if(Array.isArray(raw[k]))d[k]=raw[k];if(Array.isArray(raw.media)){d.videos=raw.media.filter(x=>x.type==='video');d.images=raw.media.filter(x=>x.type==='image')}d.settings={...d.settings,...(raw.settings||{})};d.projects=d.projects.map(normalizeItem);d.videos=d.videos.map(normalizeItem);d.images=d.images.map(normalizeItem);return d}
function load(){try{let raw=localStorage.getItem(KEY);if(!raw){for(const k of LEGACY){raw=localStorage.getItem(k);if(raw)break}}const s=migrate(raw?JSON.parse(raw):null);localStorage.setItem(KEY,JSON.stringify(s));return s}catch{return clone(defaults)}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(DB_STORE))r.result.createObjectStore(DB_STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function getBlob(id){if(!id)return null;const db=await openDb();return new Promise((res,rej)=>{const r=db.transaction(DB_STORE).objectStore(DB_STORE).get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function assetSrc(item){if(item.assetId){const b=await getBlob(item.assetId);if(b)return URL.createObjectURL(b)}return item.url||item.image||''}
function youtubeId(url=''){const m=url.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|shorts\/|embed\/))([\w-]{6,})/);return m?m[1]:''}
function setWhatsapp(a,number,text='Olá! Conheci a Frame X Studio pelo site e gostaria de conversar sobre um projeto.'){if(a)a.href=`https://wa.me/${number}?text=${encodeURIComponent(text)}`}
function toast(t){const el=$('#toast');if(!el)return;el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function screenshotUrl(url=''){if(!/^https?:\/\//i.test(url))return '';return `https://image.thum.io/get/fullpage/noanimate/width/1600/${encodeURIComponent(url)}`}
let selectedCategory='Todos',projectLimit=4,videoIndex=0,imageIndex=0;

async function render(){const s=load(),x=s.settings;const words=(x.heroTitle||defaults.settings.heroTitle).split(' '),cut=Math.ceil(words.length*.55);$('#heroTitle').innerHTML=`${esc(words.slice(0,cut).join(' '))} <em>${esc(words.slice(cut).join(' '))}</em>`;$('#heroText').textContent=x.heroText;['topWhatsapp','heroWhatsapp','contactWhatsapp'].forEach(id=>setWhatsapp($('#'+id),x.whatsapp));setWhatsapp($('#modelWhatsapp'),x.whatsapp,'Olá! Quero saber mais sobre a criação de uma modelo virtual para TikTok Shop.');$('#contactPhone').textContent=x.phone;$('#contactLocation').innerHTML=esc(x.location).replace(/\n/g,'<br>');$('#contactSocial').textContent=x.socialLabel;const socials=[];if(x.instagramPersonal)socials.push(`<a href="${esc(x.instagramPersonal)}" target="_blank" rel="noopener">Instagram Caio ↗</a>`);if(x.instagramFrameX)socials.push(`<a href="${esc(x.instagramFrameX)}" target="_blank" rel="noopener">Instagram Frame X ↗</a>`);$('#socialLinks').innerHTML=socials.join('');$('#footerSocials').innerHTML=socials.join('');renderProjectFilters(s);await renderProjects(s);await renderVideos(s);await renderImages(s);renderReviews(s)}
function renderProjectFilters(s){const cats=['Todos',...new Set(s.projects.filter(x=>x.published!==false&&x.status!=='draft').map(x=>x.category).filter(Boolean))];$('#projectFilters').innerHTML=cats.map(c=>`<button class="${c===selectedCategory?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.cat;projectLimit=4;render()})}
async function renderProjects(s){const all=s.projects.filter(p=>p.published!==false&&p.status!=='draft'&&(selectedCategory==='Todos'||p.category===selectedCategory)).sort((a,b)=>(Number(b.featured)-Number(a.featured))||((a.order||0)-(b.order||0))),list=all.slice(0,projectLimit),grid=$('#projectGrid');const cards=[];for(let i=0;i<list.length;i++){const p=list[i];let src='';if(p.previewMode==='image')src=await assetSrc(p);if(!src&&p.image)src=p.image;if(!src&&p.previewMode==='auto')src=screenshotUrl(p.url);if(!src)src='assets/project-1.png';cards.push(`<article class="project ${p.featured?'featured':''}"><div class="browser"><div class="browserbar"><i></i><i></i><i></i><span>FRAME X · PROJETO</span></div><div class="screen"><img src="${esc(src)}" alt="Prévia de ${esc(p.name)}" loading="lazy" onerror="this.onerror=null;this.src='assets/project-1.png'"><a class="viewSiteOverlay" href="${esc(p.url||'#')}" target="_blank" rel="noopener">VER SITE ↗</a></div></div><div class="projectInfo"><div><span>${esc(p.category||'Projeto')}</span><h3>${esc(p.name||'Projeto')}</h3><p>${esc(p.description||'')}</p></div><a class="roundArrow" href="${esc(p.url||'#')}" target="_blank" rel="noopener">↗</a></div></article>`)}grid.innerHTML=cards.join('');$('#emptyProjects').classList.toggle('hidden',!!all.length);$('#moreProjects').style.display=all.length>projectLimit?'inline-flex':'none'}
async function buildVideo(v){const yt=youtubeId(v.url),src=await assetSrc(v);return `<article class="coverItem"><div class="coverMedia">${yt?`<iframe src="https://www.youtube.com/embed/${yt}?rel=0" title="${esc(v.title)}" loading="lazy" allowfullscreen></iframe>`:src?`<video src="${esc(src)}" controls preload="metadata" playsinline></video>`:'<div class="emptyState">Sem mídia</div>'}</div><div class="coverMeta"><small>${esc(v.category||'VÍDEO')}</small><b>${esc(v.title||'Vídeo')}</b></div></article>`}
async function renderVideos(s){const list=s.videos.filter(v=>v.published!==false&&v.status!=='draft').sort((a,b)=>(Number(b.featured)-Number(a.featured))||((a.order||0)-(b.order||0)));$('#emptyVideos').style.display=list.length?'none':'block';if(!list.length){$('#videoTrack').innerHTML='';return}videoIndex=Math.min(videoIndex,list.length-1);const html=[];for(const v of list)html.push(await buildVideo(v));$('#videoTrack').innerHTML=html.join('');setupCoverflow('video',list.length)}
async function renderImages(s){const list=s.images.filter(v=>v.published!==false&&v.status!=='draft').sort((a,b)=>(Number(b.featured)-Number(a.featured))||((a.order||0)-(b.order||0)));$('#emptyImages').style.display=list.length?'none':'block';if(!list.length){$('#imageTrack').innerHTML='';return}imageIndex=Math.min(imageIndex,list.length-1);const html=[];for(const v of list){const src=await assetSrc(v);html.push(`<button class="coverItem" data-src="${esc(src)}" data-title="${esc(v.title||'Imagem')}" data-desc="${esc(v.description||'')}"><img src="${esc(src)}" alt="${esc(v.title||'Imagem')}"><div class="coverMeta"><small>${esc(v.category||'IMAGEM')}</small><b>${esc(v.title||'Imagem')}</b></div></button>`)}$('#imageTrack').innerHTML=html.join('');setupCoverflow('image',list.length);$$('#imageTrack .coverItem').forEach(el=>el.onclick=()=>openImage(el.dataset.src,el.dataset.title,el.dataset.desc))}
function setupCoverflow(type,len){const track=$(`#${type}Track`),flow=track.closest('.coverflow');function paint(){const idx=type==='video'?videoIndex:imageIndex;[...track.children].forEach((el,i)=>{const d=i-idx;el.classList.toggle('active',d===0);el.classList.toggle('near',Math.abs(d)===1);el.style.transform=d===0?'scale(1)':Math.abs(d)===1?`translateX(${d*2}%) scale(.88) rotateY(${d<0?12:-12}deg)`:`scale(.72)`});const active=track.children[idx];if(active)active.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'})}flow.querySelector('.prev').onclick=()=>{if(type==='video')videoIndex=(videoIndex-1+len)%len;else imageIndex=(imageIndex-1+len)%len;paint()};flow.querySelector('.next').onclick=()=>{if(type==='video')videoIndex=(videoIndex+1)%len;else imageIndex=(imageIndex+1)%len;paint()};let start=0;track.onpointerdown=e=>start=e.clientX;track.onpointerup=e=>{const dx=e.clientX-start;if(Math.abs(dx)>40)(dx<0?flow.querySelector('.next'):flow.querySelector('.prev')).click()};paint()}
function openImage(src,title,desc){$('#lightboxContent').innerHTML=`<img src="${esc(src)}" alt="${esc(title)}"><div><h3>${esc(title)}</h3><p>${esc(desc)}</p></div>`;$('#lightbox').classList.remove('hidden')}
function renderReviews(s){const list=s.reviews.filter(r=>r.approved);$('#reviewGrid').innerHTML=list.map(r=>`<article class="review glass"><div class="stars">${'★'.repeat(r.rating||5)}</div><p>“${esc(r.text)}”</p><div class="person"><span>${esc((r.name||'?')[0])}</span><div><b>${esc(r.name)}</b>${r.role?`<small>${esc(r.role)}</small>`:''}</div></div></article>`).join('')}
function submitLead(form){const fd=new FormData(form),s=load(),lead={id:crypto.randomUUID?.()||String(Date.now()),name:fd.get('name'),whatsapp:fd.get('whatsapp'),email:fd.get('email'),service:fd.get('service'),idea:fd.get('idea'),status:'Novo'};s.leads.unshift(lead);save(s);form.reset();toast('Recebi sua ideia. Vou falar com você pelo WhatsApp!')}
render();$('#moreProjects').onclick=()=>{projectLimit+=4;render()};$('#menuBtn').onclick=()=>document.querySelector('nav').classList.toggle('open');$('#quickLeadForm').onsubmit=e=>{e.preventDefault();submitLead(e.currentTarget)};window.addEventListener('storage',render);$('.lightboxClose').onclick=()=>$('#lightbox').classList.add('hidden');$('#lightbox').onclick=e=>{if(e.target.id==='lightbox')$('#lightbox').classList.add('hidden')};
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.08});$$('.reveal').forEach(el=>io.observe(el));let counted=false;new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&!counted){counted=true;$$('[data-count]').forEach(el=>{const end=+el.dataset.count,t0=performance.now();function tick(t){const p=Math.min(1,(t-t0)/900);el.textContent=Math.round(end*p)+(end===100?'%':'');if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)})}}),{threshold:.3}).observe($('#stats'));
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',`${e.clientX}px`);document.documentElement.style.setProperty('--my',`${e.clientY}px`);$$('.glass,.service,.review').forEach(el=>{const r=el.getBoundingClientRect();el.style.setProperty('--cx',`${e.clientX-r.left}px`);el.style.setProperty('--cy',`${e.clientY-r.top}px`)})},{passive:true})}
